### ISSUE TITLE
How to see host down 

### ISSUE THREAD

**Issue by akoup** [aelse/dashing-nagios#10]
Hi, the widget working and is great. 

But i can only see the services problem, how can i see the host down ?

Thank's

**Comment by akoup** [comment]
Hi,
Of course i have trying many things before to post my request.
Like "unacked = nag.host_status(:all)" but nothing

Can you help me with an example.

Thank's

**Comment by Jean-Mercier** [comment]
dit you find a solution or example for this ?

A Down host is not displaying any error on smashing

**Comment by Jean-Mercier** [comment]
Ok found a way to have this i search the number of time the word DOWN appear on the hostgroups_detail return 

on nagios.rb add

  unacked_host = nag.hostgroups_detail (hostgroup = "all")
  unacked_hoststring = unacked_host.to_s
  critical_host_count = unacked_hoststring.scan(/\w+/).count("DOWN")
 

    critical_count = critical_host_count
