### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by babyhuey23** [aelse/dashing-nagios#3]
When I run dashing, I get this error and no data shows up:

scheduler caught exception:
invalid date

I am running nagios 3.5.1

**Comment by arnaudmm** [comment]
worked for me too, thx!

**Comment by Zabeus** [comment]
iso8601 worked for me.

**Comment by aelse** [comment]
Thanks for all the comments. Due to repeated user feedback that @x solution works i've made the change even though i'm unable to test it myself (no longer a nagios or dashing user).
