### ISSUE TITLE
Black criticals/warnings, no updates

### ISSUE THREAD

**Issue by christrotter** [aelse/dashing-nagios#7]
I'm getting a screen like below:
![image](https://cloud.githubusercontent.com/assets/8292406/5465247/cea4ebec-8561-11e4-8981-4704d5860d7d.png)

Not getting any errors or 'cannot connect to Nagios' warnings, just a black screen.  If I ctrl+C the running dashing instance, the black box turns green and says 'last updated...(time)'.  The only exceptions being caught are 'invalid date'.
![image](https://cloud.githubusercontent.com/assets/8292406/5465265/1b6a7c08-8562-11e4-9fdf-848107d45760.png)

``` shell
================================================================================
scheduler caught exception:
invalid date
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/nagiosharder-827b774a2cfd/lib/nagiosharder.rb:587:in `strptime'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/nagiosharder-827b774a2cfd/lib/nagiosharder.rb:587:in `block in parse_status_html'
/usr/local/rvm/gems/ruby-2.1.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `upto'
/usr/local/rvm/gems/ruby-2.1.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `each'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/nagiosharder-827b774a2cfd/lib/nagiosharder.rb:524:in `parse_status_html'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/nagiosharder-827b774a2cfd/lib/nagiosharder.rb:269:in `service_status'
/srv/dashing/prodsupport_dashboard/jobs/nagios.rb:30:in `block (2 levels) in <top (required)>'
/srv/dashing/prodsupport_dashboard/jobs/nagios.rb:10:in `each'
/srv/dashing/prodsupport_dashboard/jobs/nagios.rb:10:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/rvm/gems/ruby-2.1.2/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/rvm/gems/ruby-2.1.2/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

My environments block looks like this: 

``` ruby
  environments = {
    ng02: { url: 'http://ng02/site/nagios/cgi-bin/', username: 'omdadmin', password: 'passHere' },
    ng01: { url: 'http://ng01/nagios/cgi-bin/', username: 'nagiosadmin', password: 'passHere' },
  }
```

As you can see, trying from both OMD (1.10) Nagios (3.5.0) and Nagios Core (3.2.3)

I think I followed all the instructions...is there something obvious I'm missing here?

**Comment by ferBo** [comment]
Hi! Same issue here! I was getting the exception, tried issue #3 and fixed the exception problem, but still not displaying any information on the dashboard. I can see in Apache logs that the information is being accessed correctly:

    127.0.0.1 - nagiosadmin [14/Apr/2015:19:06:35 -0300] "GET /cgi-bin/nagios3/status.cgi?hoststatustypes=2&servicestatustypes=20&serviceprops=42&servicegroup=all&style=detail&embedded=1&noheader=1&limit=0 HTTP/1.1" 200 4696 "-" "Ruby"

Running: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

Thank you!

**Comment by lrdshaper** [comment]
Just want to confirm that this still works with Nagios 4 using the following. Thank you!

`nachos: { url: 'http://nachos/nagios/cgi-bin', username: 'nagiosadm', password: 'passwd' },
 nag = NagiosHarder::Site.new(env[:url], env[:username], env[:password], 3, 'iso8601')`

**Comment by aelse** [comment]
Thanks for the feedback @lrdshaper!

**Comment by aelse** [comment]
I've applied the fix above to the repo. See also #3
