### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by nat3-m** [aelse/dashing-nagios#8]
Hi

I get the following error.  Any thoughts on why?

![2-11-2015 9-38-06 am](https://cloud.githubusercontent.com/assets/10961298/6149900/861dc29e-b1d1-11e4-9a66-8bf238448249.png)

![2-11-2015 9-36-45 am](https://cloud.githubusercontent.com/assets/10961298/6149881/656f9892-b1d1-11e4-8563-b4c574a7fbad.png)

**Comment by xila76** [comment]
Hi,

I have the same issue, did you really solve it ?
Issue was closed without any info... on how you solved it...
