### ISSUE TITLE
displaying alerts for a particular hostgroup in dashing

### ISSUE THREAD

**Issue by abhin123** [aelse/dashing-nagios#9]
Can we use this for displaying alerts for a particular hostgroup for example I need to display the nagios alert information for servers under PROD  hostgroup. I tried modifying the .rb file by adding hostgroup as PROD but its not working.
@aelse

**Comment by aelse** [comment]
I don't see why not. You'll need to change the service query at https://github.com/aelse/dashing-nagios/blob/master/jobs/nagios.rb#L12 to get the list of servers in that hostgroup.

Looking at the nagiosharder source, maybe by using hostgroups_summary or hostgroups_detail? https://github.com/railsmachine/nagiosharder/blob/master/lib/nagiosharder.rb#L276

**Comment by abhin123** [comment]
This is my .rb file. I want to display the alerts for PROD environment only
SCHEDULER.every '30s' do
  require 'bundler/setup'
  require 'nagiosharder'

  environments = {
  n: { url: 'http://**.**.**.**/***/nagios/cgi-bin/', username: '***', password: '**' }
  }

  environments.each do |key, env|
    nag = NagiosHarder::Site.new(env[:url], env[:username], env[:password], 3, 'iso8601')
    unacked = nag.service_status(:hostgroup => [PROD] , :host_status_types => [:all], :service_status_types => [:warning, :critical], :service_props => [:hard_state, :no_scheduled_downtime, :state_unacknowledged, :checks_enabled])

    critical_count = 0
    warning_count = 0
    unacked.each do |alert|
      if alert["status"].eql? "CRITICAL"
        critical_count += 1
      elsif alert["status"].eql? "WARNING"
        warning_count += 1
      end
    end

    # nagiosharder may not alert us to a problem querying nagios.
    # If no problems found check that we fetch service status and
    # expect to find more than 0 entries.
    error = false
    if critical_count == 0 and warning_count == 0
      if nag.service_status.length == 0
        error = true
      end
    end

    if error
      # Send an empty payload, which the widget treats as an error
      send_event('nagio-' + key.to_s, { })
    else
      send_event('nagio-' + key.to_s, { criticals: critical_count, warnings: warning_count })
    end
  end
end

**Comment by aelse** [comment]
Hi @abhin123, I can't provide programming support for your particular situation. Good luck :)

**Comment by abhin123** [comment]
@aelse  Thanks for your suggestions. Can you please help me with the changes which needs to be modified in  the service query at https://github.com/aelse/dashing-nagios/blob/master/jobs/nagios.rb#L12 to get the list of servers in that hostgroup. (here I want to fetch the details for the hostgroup PROD)
